# *** DO NOT EDIT ***
# Auto-generated from binaryen-c.h
from enum import IntEnum, unique

from nxbinaryen.capi import BinaryenOp
from nxbinaryen.binaryen import lib

__all__ = [
    'BinaryOp',
    'BrOnOp',
    'RefAsOp',
    'SIMDExtractOp',
    'SIMDLoadOp',
    'SIMDLoadStoreLaneOp',
    'SIMDReplaceOp',
    'SIMDShiftOp',
    'SIMDTernaryOp',
    'StringAsOp',
    'StringEncodeOp',
    'StringEqOp',
    'StringIterMoveOp',
    'StringMeasureOp',
    'StringNewOp',
    'StringSliceWTFOp',
    'UnaryOp',
]


@unique
class BinaryOp(IntEnum):
    AddFloat32: BinaryenOp = lib.BinaryenAddFloat32()
    AddFloat64: BinaryenOp = lib.BinaryenAddFloat64()
    AddInt32: BinaryenOp = lib.BinaryenAddInt32()
    AddInt64: BinaryenOp = lib.BinaryenAddInt64()
    AddSatSVecI16x8: BinaryenOp = lib.BinaryenAddSatSVecI16x8()
    AddSatSVecI8x16: BinaryenOp = lib.BinaryenAddSatSVecI8x16()
    AddSatUVecI16x8: BinaryenOp = lib.BinaryenAddSatUVecI16x8()
    AddSatUVecI8x16: BinaryenOp = lib.BinaryenAddSatUVecI8x16()
    AddVecF32x4: BinaryenOp = lib.BinaryenAddVecF32x4()
    AddVecF64x2: BinaryenOp = lib.BinaryenAddVecF64x2()
    AddVecI16x8: BinaryenOp = lib.BinaryenAddVecI16x8()
    AddVecI32x4: BinaryenOp = lib.BinaryenAddVecI32x4()
    AddVecI64x2: BinaryenOp = lib.BinaryenAddVecI64x2()
    AddVecI8x16: BinaryenOp = lib.BinaryenAddVecI8x16()
    AndInt32: BinaryenOp = lib.BinaryenAndInt32()
    AndInt64: BinaryenOp = lib.BinaryenAndInt64()
    AndNotVec128: BinaryenOp = lib.BinaryenAndNotVec128()
    AndVec128: BinaryenOp = lib.BinaryenAndVec128()
    AvgrUVecI16x8: BinaryenOp = lib.BinaryenAvgrUVecI16x8()
    AvgrUVecI8x16: BinaryenOp = lib.BinaryenAvgrUVecI8x16()
    CopySignFloat32: BinaryenOp = lib.BinaryenCopySignFloat32()
    CopySignFloat64: BinaryenOp = lib.BinaryenCopySignFloat64()
    DivFloat32: BinaryenOp = lib.BinaryenDivFloat32()
    DivFloat64: BinaryenOp = lib.BinaryenDivFloat64()
    DivSInt32: BinaryenOp = lib.BinaryenDivSInt32()
    DivSInt64: BinaryenOp = lib.BinaryenDivSInt64()
    DivUInt32: BinaryenOp = lib.BinaryenDivUInt32()
    DivUInt64: BinaryenOp = lib.BinaryenDivUInt64()
    DivVecF32x4: BinaryenOp = lib.BinaryenDivVecF32x4()
    DivVecF64x2: BinaryenOp = lib.BinaryenDivVecF64x2()
    DotI8x16I7x16SToVecI16x8: BinaryenOp = lib.BinaryenDotI8x16I7x16SToVecI16x8()
    DotSVecI16x8ToVecI32x4: BinaryenOp = lib.BinaryenDotSVecI16x8ToVecI32x4()
    EqFloat32: BinaryenOp = lib.BinaryenEqFloat32()
    EqFloat64: BinaryenOp = lib.BinaryenEqFloat64()
    EqInt32: BinaryenOp = lib.BinaryenEqInt32()
    EqInt64: BinaryenOp = lib.BinaryenEqInt64()
    EqVecF32x4: BinaryenOp = lib.BinaryenEqVecF32x4()
    EqVecF64x2: BinaryenOp = lib.BinaryenEqVecF64x2()
    EqVecI16x8: BinaryenOp = lib.BinaryenEqVecI16x8()
    EqVecI32x4: BinaryenOp = lib.BinaryenEqVecI32x4()
    EqVecI64x2: BinaryenOp = lib.BinaryenEqVecI64x2()
    EqVecI8x16: BinaryenOp = lib.BinaryenEqVecI8x16()
    ExtMulHighSVecI16x8: BinaryenOp = lib.BinaryenExtMulHighSVecI16x8()
    ExtMulHighSVecI32x4: BinaryenOp = lib.BinaryenExtMulHighSVecI32x4()
    ExtMulHighSVecI64x2: BinaryenOp = lib.BinaryenExtMulHighSVecI64x2()
    ExtMulHighUVecI16x8: BinaryenOp = lib.BinaryenExtMulHighUVecI16x8()
    ExtMulHighUVecI32x4: BinaryenOp = lib.BinaryenExtMulHighUVecI32x4()
    ExtMulHighUVecI64x2: BinaryenOp = lib.BinaryenExtMulHighUVecI64x2()
    ExtMulLowSVecI16x8: BinaryenOp = lib.BinaryenExtMulLowSVecI16x8()
    ExtMulLowSVecI32x4: BinaryenOp = lib.BinaryenExtMulLowSVecI32x4()
    ExtMulLowSVecI64x2: BinaryenOp = lib.BinaryenExtMulLowSVecI64x2()
    ExtMulLowUVecI16x8: BinaryenOp = lib.BinaryenExtMulLowUVecI16x8()
    ExtMulLowUVecI32x4: BinaryenOp = lib.BinaryenExtMulLowUVecI32x4()
    ExtMulLowUVecI64x2: BinaryenOp = lib.BinaryenExtMulLowUVecI64x2()
    GeFloat32: BinaryenOp = lib.BinaryenGeFloat32()
    GeFloat64: BinaryenOp = lib.BinaryenGeFloat64()
    GeSInt32: BinaryenOp = lib.BinaryenGeSInt32()
    GeSInt64: BinaryenOp = lib.BinaryenGeSInt64()
    GeSVecI16x8: BinaryenOp = lib.BinaryenGeSVecI16x8()
    GeSVecI32x4: BinaryenOp = lib.BinaryenGeSVecI32x4()
    GeSVecI64x2: BinaryenOp = lib.BinaryenGeSVecI64x2()
    GeSVecI8x16: BinaryenOp = lib.BinaryenGeSVecI8x16()
    GeUInt32: BinaryenOp = lib.BinaryenGeUInt32()
    GeUInt64: BinaryenOp = lib.BinaryenGeUInt64()
    GeUVecI16x8: BinaryenOp = lib.BinaryenGeUVecI16x8()
    GeUVecI32x4: BinaryenOp = lib.BinaryenGeUVecI32x4()
    GeUVecI8x16: BinaryenOp = lib.BinaryenGeUVecI8x16()
    GeVecF32x4: BinaryenOp = lib.BinaryenGeVecF32x4()
    GeVecF64x2: BinaryenOp = lib.BinaryenGeVecF64x2()
    GtFloat32: BinaryenOp = lib.BinaryenGtFloat32()
    GtFloat64: BinaryenOp = lib.BinaryenGtFloat64()
    GtSInt32: BinaryenOp = lib.BinaryenGtSInt32()
    GtSInt64: BinaryenOp = lib.BinaryenGtSInt64()
    GtSVecI16x8: BinaryenOp = lib.BinaryenGtSVecI16x8()
    GtSVecI32x4: BinaryenOp = lib.BinaryenGtSVecI32x4()
    GtSVecI64x2: BinaryenOp = lib.BinaryenGtSVecI64x2()
    GtSVecI8x16: BinaryenOp = lib.BinaryenGtSVecI8x16()
    GtUInt32: BinaryenOp = lib.BinaryenGtUInt32()
    GtUInt64: BinaryenOp = lib.BinaryenGtUInt64()
    GtUVecI16x8: BinaryenOp = lib.BinaryenGtUVecI16x8()
    GtUVecI32x4: BinaryenOp = lib.BinaryenGtUVecI32x4()
    GtUVecI8x16: BinaryenOp = lib.BinaryenGtUVecI8x16()
    GtVecF32x4: BinaryenOp = lib.BinaryenGtVecF32x4()
    GtVecF64x2: BinaryenOp = lib.BinaryenGtVecF64x2()
    LeFloat32: BinaryenOp = lib.BinaryenLeFloat32()
    LeFloat64: BinaryenOp = lib.BinaryenLeFloat64()
    LeSInt32: BinaryenOp = lib.BinaryenLeSInt32()
    LeSInt64: BinaryenOp = lib.BinaryenLeSInt64()
    LeSVecI16x8: BinaryenOp = lib.BinaryenLeSVecI16x8()
    LeSVecI32x4: BinaryenOp = lib.BinaryenLeSVecI32x4()
    LeSVecI64x2: BinaryenOp = lib.BinaryenLeSVecI64x2()
    LeSVecI8x16: BinaryenOp = lib.BinaryenLeSVecI8x16()
    LeUInt32: BinaryenOp = lib.BinaryenLeUInt32()
    LeUInt64: BinaryenOp = lib.BinaryenLeUInt64()
    LeUVecI16x8: BinaryenOp = lib.BinaryenLeUVecI16x8()
    LeUVecI32x4: BinaryenOp = lib.BinaryenLeUVecI32x4()
    LeUVecI8x16: BinaryenOp = lib.BinaryenLeUVecI8x16()
    LeVecF32x4: BinaryenOp = lib.BinaryenLeVecF32x4()
    LeVecF64x2: BinaryenOp = lib.BinaryenLeVecF64x2()
    LtFloat32: BinaryenOp = lib.BinaryenLtFloat32()
    LtFloat64: BinaryenOp = lib.BinaryenLtFloat64()
    LtSInt32: BinaryenOp = lib.BinaryenLtSInt32()
    LtSInt64: BinaryenOp = lib.BinaryenLtSInt64()
    LtSVecI16x8: BinaryenOp = lib.BinaryenLtSVecI16x8()
    LtSVecI32x4: BinaryenOp = lib.BinaryenLtSVecI32x4()
    LtSVecI64x2: BinaryenOp = lib.BinaryenLtSVecI64x2()
    LtSVecI8x16: BinaryenOp = lib.BinaryenLtSVecI8x16()
    LtUInt32: BinaryenOp = lib.BinaryenLtUInt32()
    LtUInt64: BinaryenOp = lib.BinaryenLtUInt64()
    LtUVecI16x8: BinaryenOp = lib.BinaryenLtUVecI16x8()
    LtUVecI32x4: BinaryenOp = lib.BinaryenLtUVecI32x4()
    LtUVecI8x16: BinaryenOp = lib.BinaryenLtUVecI8x16()
    LtVecF32x4: BinaryenOp = lib.BinaryenLtVecF32x4()
    LtVecF64x2: BinaryenOp = lib.BinaryenLtVecF64x2()
    MaxFloat32: BinaryenOp = lib.BinaryenMaxFloat32()
    MaxFloat64: BinaryenOp = lib.BinaryenMaxFloat64()
    MaxSVecI16x8: BinaryenOp = lib.BinaryenMaxSVecI16x8()
    MaxSVecI32x4: BinaryenOp = lib.BinaryenMaxSVecI32x4()
    MaxSVecI8x16: BinaryenOp = lib.BinaryenMaxSVecI8x16()
    MaxUVecI16x8: BinaryenOp = lib.BinaryenMaxUVecI16x8()
    MaxUVecI32x4: BinaryenOp = lib.BinaryenMaxUVecI32x4()
    MaxUVecI8x16: BinaryenOp = lib.BinaryenMaxUVecI8x16()
    MaxVecF32x4: BinaryenOp = lib.BinaryenMaxVecF32x4()
    MaxVecF64x2: BinaryenOp = lib.BinaryenMaxVecF64x2()
    MinFloat32: BinaryenOp = lib.BinaryenMinFloat32()
    MinFloat64: BinaryenOp = lib.BinaryenMinFloat64()
    MinSVecI16x8: BinaryenOp = lib.BinaryenMinSVecI16x8()
    MinSVecI32x4: BinaryenOp = lib.BinaryenMinSVecI32x4()
    MinSVecI8x16: BinaryenOp = lib.BinaryenMinSVecI8x16()
    MinUVecI16x8: BinaryenOp = lib.BinaryenMinUVecI16x8()
    MinUVecI32x4: BinaryenOp = lib.BinaryenMinUVecI32x4()
    MinUVecI8x16: BinaryenOp = lib.BinaryenMinUVecI8x16()
    MinVecF32x4: BinaryenOp = lib.BinaryenMinVecF32x4()
    MinVecF64x2: BinaryenOp = lib.BinaryenMinVecF64x2()
    MulFloat32: BinaryenOp = lib.BinaryenMulFloat32()
    MulFloat64: BinaryenOp = lib.BinaryenMulFloat64()
    MulInt32: BinaryenOp = lib.BinaryenMulInt32()
    MulInt64: BinaryenOp = lib.BinaryenMulInt64()
    MulVecF32x4: BinaryenOp = lib.BinaryenMulVecF32x4()
    MulVecF64x2: BinaryenOp = lib.BinaryenMulVecF64x2()
    MulVecI16x8: BinaryenOp = lib.BinaryenMulVecI16x8()
    MulVecI32x4: BinaryenOp = lib.BinaryenMulVecI32x4()
    MulVecI64x2: BinaryenOp = lib.BinaryenMulVecI64x2()
    NarrowSVecI16x8ToVecI8x16: BinaryenOp = lib.BinaryenNarrowSVecI16x8ToVecI8x16()
    NarrowSVecI32x4ToVecI16x8: BinaryenOp = lib.BinaryenNarrowSVecI32x4ToVecI16x8()
    NarrowUVecI16x8ToVecI8x16: BinaryenOp = lib.BinaryenNarrowUVecI16x8ToVecI8x16()
    NarrowUVecI32x4ToVecI16x8: BinaryenOp = lib.BinaryenNarrowUVecI32x4ToVecI16x8()
    NeFloat32: BinaryenOp = lib.BinaryenNeFloat32()
    NeFloat64: BinaryenOp = lib.BinaryenNeFloat64()
    NeInt32: BinaryenOp = lib.BinaryenNeInt32()
    NeInt64: BinaryenOp = lib.BinaryenNeInt64()
    NeVecF32x4: BinaryenOp = lib.BinaryenNeVecF32x4()
    NeVecF64x2: BinaryenOp = lib.BinaryenNeVecF64x2()
    NeVecI16x8: BinaryenOp = lib.BinaryenNeVecI16x8()
    NeVecI32x4: BinaryenOp = lib.BinaryenNeVecI32x4()
    NeVecI64x2: BinaryenOp = lib.BinaryenNeVecI64x2()
    NeVecI8x16: BinaryenOp = lib.BinaryenNeVecI8x16()
    OrInt32: BinaryenOp = lib.BinaryenOrInt32()
    OrInt64: BinaryenOp = lib.BinaryenOrInt64()
    OrVec128: BinaryenOp = lib.BinaryenOrVec128()
    PMaxVecF32x4: BinaryenOp = lib.BinaryenPMaxVecF32x4()
    PMaxVecF64x2: BinaryenOp = lib.BinaryenPMaxVecF64x2()
    PMinVecF32x4: BinaryenOp = lib.BinaryenPMinVecF32x4()
    PMinVecF64x2: BinaryenOp = lib.BinaryenPMinVecF64x2()
    Q15MulrSatSVecI16x8: BinaryenOp = lib.BinaryenQ15MulrSatSVecI16x8()
    RelaxedMaxVecF32x4: BinaryenOp = lib.BinaryenRelaxedMaxVecF32x4()
    RelaxedMaxVecF64x2: BinaryenOp = lib.BinaryenRelaxedMaxVecF64x2()
    RelaxedMinVecF32x4: BinaryenOp = lib.BinaryenRelaxedMinVecF32x4()
    RelaxedMinVecF64x2: BinaryenOp = lib.BinaryenRelaxedMinVecF64x2()
    RelaxedQ15MulrSVecI16x8: BinaryenOp = lib.BinaryenRelaxedQ15MulrSVecI16x8()
    RelaxedSwizzleVecI8x16: BinaryenOp = lib.BinaryenRelaxedSwizzleVecI8x16()
    RemSInt32: BinaryenOp = lib.BinaryenRemSInt32()
    RemSInt64: BinaryenOp = lib.BinaryenRemSInt64()
    RemUInt32: BinaryenOp = lib.BinaryenRemUInt32()
    RemUInt64: BinaryenOp = lib.BinaryenRemUInt64()
    RotLInt32: BinaryenOp = lib.BinaryenRotLInt32()
    RotLInt64: BinaryenOp = lib.BinaryenRotLInt64()
    RotRInt32: BinaryenOp = lib.BinaryenRotRInt32()
    RotRInt64: BinaryenOp = lib.BinaryenRotRInt64()
    ShlInt32: BinaryenOp = lib.BinaryenShlInt32()
    ShlInt64: BinaryenOp = lib.BinaryenShlInt64()
    ShrSInt32: BinaryenOp = lib.BinaryenShrSInt32()
    ShrSInt64: BinaryenOp = lib.BinaryenShrSInt64()
    ShrUInt32: BinaryenOp = lib.BinaryenShrUInt32()
    ShrUInt64: BinaryenOp = lib.BinaryenShrUInt64()
    SubFloat32: BinaryenOp = lib.BinaryenSubFloat32()
    SubFloat64: BinaryenOp = lib.BinaryenSubFloat64()
    SubInt32: BinaryenOp = lib.BinaryenSubInt32()
    SubInt64: BinaryenOp = lib.BinaryenSubInt64()
    SubSatSVecI16x8: BinaryenOp = lib.BinaryenSubSatSVecI16x8()
    SubSatSVecI8x16: BinaryenOp = lib.BinaryenSubSatSVecI8x16()
    SubSatUVecI16x8: BinaryenOp = lib.BinaryenSubSatUVecI16x8()
    SubSatUVecI8x16: BinaryenOp = lib.BinaryenSubSatUVecI8x16()
    SubVecF32x4: BinaryenOp = lib.BinaryenSubVecF32x4()
    SubVecF64x2: BinaryenOp = lib.BinaryenSubVecF64x2()
    SubVecI16x8: BinaryenOp = lib.BinaryenSubVecI16x8()
    SubVecI32x4: BinaryenOp = lib.BinaryenSubVecI32x4()
    SubVecI64x2: BinaryenOp = lib.BinaryenSubVecI64x2()
    SubVecI8x16: BinaryenOp = lib.BinaryenSubVecI8x16()
    SwizzleVecI8x16: BinaryenOp = lib.BinaryenSwizzleVecI8x16()
    XorInt32: BinaryenOp = lib.BinaryenXorInt32()
    XorInt64: BinaryenOp = lib.BinaryenXorInt64()
    XorVec128: BinaryenOp = lib.BinaryenXorVec128()


@unique
class BrOnOp(IntEnum):
    BrOnCast: BinaryenOp = lib.BinaryenBrOnCast()
    BrOnCastFail: BinaryenOp = lib.BinaryenBrOnCastFail()
    BrOnNonNull: BinaryenOp = lib.BinaryenBrOnNonNull()
    BrOnNull: BinaryenOp = lib.BinaryenBrOnNull()


@unique
class RefAsOp(IntEnum):
    RefAsNonNull: BinaryenOp = lib.BinaryenRefAsNonNull()


@unique
class SIMDExtractOp(IntEnum):
    ExtractLaneSVecI16x8: BinaryenOp = lib.BinaryenExtractLaneSVecI16x8()
    ExtractLaneSVecI8x16: BinaryenOp = lib.BinaryenExtractLaneSVecI8x16()
    ExtractLaneUVecI16x8: BinaryenOp = lib.BinaryenExtractLaneUVecI16x8()
    ExtractLaneUVecI8x16: BinaryenOp = lib.BinaryenExtractLaneUVecI8x16()
    ExtractLaneVecF32x4: BinaryenOp = lib.BinaryenExtractLaneVecF32x4()
    ExtractLaneVecF64x2: BinaryenOp = lib.BinaryenExtractLaneVecF64x2()
    ExtractLaneVecI32x4: BinaryenOp = lib.BinaryenExtractLaneVecI32x4()
    ExtractLaneVecI64x2: BinaryenOp = lib.BinaryenExtractLaneVecI64x2()


@unique
class SIMDLoadOp(IntEnum):
    Load16SplatVec128: BinaryenOp = lib.BinaryenLoad16SplatVec128()
    Load16x4SVec128: BinaryenOp = lib.BinaryenLoad16x4SVec128()
    Load16x4UVec128: BinaryenOp = lib.BinaryenLoad16x4UVec128()
    Load32SplatVec128: BinaryenOp = lib.BinaryenLoad32SplatVec128()
    Load32ZeroVec128: BinaryenOp = lib.BinaryenLoad32ZeroVec128()
    Load32x2SVec128: BinaryenOp = lib.BinaryenLoad32x2SVec128()
    Load32x2UVec128: BinaryenOp = lib.BinaryenLoad32x2UVec128()
    Load64SplatVec128: BinaryenOp = lib.BinaryenLoad64SplatVec128()
    Load64ZeroVec128: BinaryenOp = lib.BinaryenLoad64ZeroVec128()
    Load8SplatVec128: BinaryenOp = lib.BinaryenLoad8SplatVec128()
    Load8x8SVec128: BinaryenOp = lib.BinaryenLoad8x8SVec128()
    Load8x8UVec128: BinaryenOp = lib.BinaryenLoad8x8UVec128()


@unique
class SIMDLoadStoreLaneOp(IntEnum):
    Load16LaneVec128: BinaryenOp = lib.BinaryenLoad16LaneVec128()
    Load32LaneVec128: BinaryenOp = lib.BinaryenLoad32LaneVec128()
    Load64LaneVec128: BinaryenOp = lib.BinaryenLoad64LaneVec128()
    Load8LaneVec128: BinaryenOp = lib.BinaryenLoad8LaneVec128()
    Store16LaneVec128: BinaryenOp = lib.BinaryenStore16LaneVec128()
    Store32LaneVec128: BinaryenOp = lib.BinaryenStore32LaneVec128()
    Store64LaneVec128: BinaryenOp = lib.BinaryenStore64LaneVec128()
    Store8LaneVec128: BinaryenOp = lib.BinaryenStore8LaneVec128()


@unique
class SIMDReplaceOp(IntEnum):
    ReplaceLaneVecF32x4: BinaryenOp = lib.BinaryenReplaceLaneVecF32x4()
    ReplaceLaneVecF64x2: BinaryenOp = lib.BinaryenReplaceLaneVecF64x2()
    ReplaceLaneVecI16x8: BinaryenOp = lib.BinaryenReplaceLaneVecI16x8()
    ReplaceLaneVecI32x4: BinaryenOp = lib.BinaryenReplaceLaneVecI32x4()
    ReplaceLaneVecI64x2: BinaryenOp = lib.BinaryenReplaceLaneVecI64x2()
    ReplaceLaneVecI8x16: BinaryenOp = lib.BinaryenReplaceLaneVecI8x16()


@unique
class SIMDShiftOp(IntEnum):
    ShlVecI16x8: BinaryenOp = lib.BinaryenShlVecI16x8()
    ShlVecI32x4: BinaryenOp = lib.BinaryenShlVecI32x4()
    ShlVecI64x2: BinaryenOp = lib.BinaryenShlVecI64x2()
    ShlVecI8x16: BinaryenOp = lib.BinaryenShlVecI8x16()
    ShrSVecI16x8: BinaryenOp = lib.BinaryenShrSVecI16x8()
    ShrSVecI32x4: BinaryenOp = lib.BinaryenShrSVecI32x4()
    ShrSVecI64x2: BinaryenOp = lib.BinaryenShrSVecI64x2()
    ShrSVecI8x16: BinaryenOp = lib.BinaryenShrSVecI8x16()
    ShrUVecI16x8: BinaryenOp = lib.BinaryenShrUVecI16x8()
    ShrUVecI32x4: BinaryenOp = lib.BinaryenShrUVecI32x4()
    ShrUVecI64x2: BinaryenOp = lib.BinaryenShrUVecI64x2()
    ShrUVecI8x16: BinaryenOp = lib.BinaryenShrUVecI8x16()


@unique
class SIMDTernaryOp(IntEnum):
    DotI8x16I7x16AddSToVecI32x4: BinaryenOp = lib.BinaryenDotI8x16I7x16AddSToVecI32x4()
    LaneselectI16x8: BinaryenOp = lib.BinaryenLaneselectI16x8()
    LaneselectI32x4: BinaryenOp = lib.BinaryenLaneselectI32x4()
    LaneselectI64x2: BinaryenOp = lib.BinaryenLaneselectI64x2()
    LaneselectI8x16: BinaryenOp = lib.BinaryenLaneselectI8x16()
    RelaxedFmaVecF32x4: BinaryenOp = lib.BinaryenRelaxedFmaVecF32x4()
    RelaxedFmaVecF64x2: BinaryenOp = lib.BinaryenRelaxedFmaVecF64x2()
    RelaxedFmsVecF32x4: BinaryenOp = lib.BinaryenRelaxedFmsVecF32x4()
    RelaxedFmsVecF64x2: BinaryenOp = lib.BinaryenRelaxedFmsVecF64x2()


@unique
class StringAsOp(IntEnum):
    StringAsIter: BinaryenOp = lib.BinaryenStringAsIter()
    StringAsWTF16: BinaryenOp = lib.BinaryenStringAsWTF16()
    StringAsWTF8: BinaryenOp = lib.BinaryenStringAsWTF8()


@unique
class StringEncodeOp(IntEnum):
    StringEncodeUTF8: BinaryenOp = lib.BinaryenStringEncodeUTF8()
    StringEncodeUTF8Array: BinaryenOp = lib.BinaryenStringEncodeUTF8Array()
    StringEncodeWTF16: BinaryenOp = lib.BinaryenStringEncodeWTF16()
    StringEncodeWTF16Array: BinaryenOp = lib.BinaryenStringEncodeWTF16Array()
    StringEncodeWTF8: BinaryenOp = lib.BinaryenStringEncodeWTF8()
    StringEncodeWTF8Array: BinaryenOp = lib.BinaryenStringEncodeWTF8Array()


@unique
class StringEqOp(IntEnum):
    StringEqCompare: BinaryenOp = lib.BinaryenStringEqCompare()
    StringEqEqual: BinaryenOp = lib.BinaryenStringEqEqual()


@unique
class StringIterMoveOp(IntEnum):
    StringIterMoveAdvance: BinaryenOp = lib.BinaryenStringIterMoveAdvance()
    StringIterMoveRewind: BinaryenOp = lib.BinaryenStringIterMoveRewind()


@unique
class StringMeasureOp(IntEnum):
    StringMeasureIsUSV: BinaryenOp = lib.BinaryenStringMeasureIsUSV()
    StringMeasureUTF8: BinaryenOp = lib.BinaryenStringMeasureUTF8()
    StringMeasureWTF16: BinaryenOp = lib.BinaryenStringMeasureWTF16()
    StringMeasureWTF16View: BinaryenOp = lib.BinaryenStringMeasureWTF16View()
    StringMeasureWTF8: BinaryenOp = lib.BinaryenStringMeasureWTF8()


@unique
class StringNewOp(IntEnum):
    StringNewFromCodePoint: BinaryenOp = lib.BinaryenStringNewFromCodePoint()
    StringNewReplace: BinaryenOp = lib.BinaryenStringNewReplace()
    StringNewReplaceArray: BinaryenOp = lib.BinaryenStringNewReplaceArray()
    StringNewUTF8: BinaryenOp = lib.BinaryenStringNewUTF8()
    StringNewUTF8Array: BinaryenOp = lib.BinaryenStringNewUTF8Array()
    StringNewWTF16: BinaryenOp = lib.BinaryenStringNewWTF16()
    StringNewWTF16Array: BinaryenOp = lib.BinaryenStringNewWTF16Array()
    StringNewWTF8: BinaryenOp = lib.BinaryenStringNewWTF8()
    StringNewWTF8Array: BinaryenOp = lib.BinaryenStringNewWTF8Array()


@unique
class StringSliceWTFOp(IntEnum):
    StringSliceWTF16: BinaryenOp = lib.BinaryenStringSliceWTF16()
    StringSliceWTF8: BinaryenOp = lib.BinaryenStringSliceWTF8()


@unique
class UnaryOp(IntEnum):
    AbsFloat32: BinaryenOp = lib.BinaryenAbsFloat32()
    AbsFloat64: BinaryenOp = lib.BinaryenAbsFloat64()
    AbsVecF32x4: BinaryenOp = lib.BinaryenAbsVecF32x4()
    AbsVecF64x2: BinaryenOp = lib.BinaryenAbsVecF64x2()
    AbsVecI16x8: BinaryenOp = lib.BinaryenAbsVecI16x8()
    AbsVecI32x4: BinaryenOp = lib.BinaryenAbsVecI32x4()
    AbsVecI64x2: BinaryenOp = lib.BinaryenAbsVecI64x2()
    AbsVecI8x16: BinaryenOp = lib.BinaryenAbsVecI8x16()
    AllTrueVecI16x8: BinaryenOp = lib.BinaryenAllTrueVecI16x8()
    AllTrueVecI32x4: BinaryenOp = lib.BinaryenAllTrueVecI32x4()
    AllTrueVecI64x2: BinaryenOp = lib.BinaryenAllTrueVecI64x2()
    AllTrueVecI8x16: BinaryenOp = lib.BinaryenAllTrueVecI8x16()
    AnyTrueVec128: BinaryenOp = lib.BinaryenAnyTrueVec128()
    BitmaskVecI16x8: BinaryenOp = lib.BinaryenBitmaskVecI16x8()
    BitmaskVecI32x4: BinaryenOp = lib.BinaryenBitmaskVecI32x4()
    BitmaskVecI64x2: BinaryenOp = lib.BinaryenBitmaskVecI64x2()
    BitmaskVecI8x16: BinaryenOp = lib.BinaryenBitmaskVecI8x16()
    CeilFloat32: BinaryenOp = lib.BinaryenCeilFloat32()
    CeilFloat64: BinaryenOp = lib.BinaryenCeilFloat64()
    CeilVecF32x4: BinaryenOp = lib.BinaryenCeilVecF32x4()
    CeilVecF64x2: BinaryenOp = lib.BinaryenCeilVecF64x2()
    ClzInt32: BinaryenOp = lib.BinaryenClzInt32()
    ClzInt64: BinaryenOp = lib.BinaryenClzInt64()
    ConvertLowSVecI32x4ToVecF64x2: BinaryenOp = lib.BinaryenConvertLowSVecI32x4ToVecF64x2()
    ConvertLowUVecI32x4ToVecF64x2: BinaryenOp = lib.BinaryenConvertLowUVecI32x4ToVecF64x2()
    ConvertSInt32ToFloat32: BinaryenOp = lib.BinaryenConvertSInt32ToFloat32()
    ConvertSInt32ToFloat64: BinaryenOp = lib.BinaryenConvertSInt32ToFloat64()
    ConvertSInt64ToFloat32: BinaryenOp = lib.BinaryenConvertSInt64ToFloat32()
    ConvertSInt64ToFloat64: BinaryenOp = lib.BinaryenConvertSInt64ToFloat64()
    ConvertSVecI32x4ToVecF32x4: BinaryenOp = lib.BinaryenConvertSVecI32x4ToVecF32x4()
    ConvertUInt32ToFloat32: BinaryenOp = lib.BinaryenConvertUInt32ToFloat32()
    ConvertUInt32ToFloat64: BinaryenOp = lib.BinaryenConvertUInt32ToFloat64()
    ConvertUInt64ToFloat32: BinaryenOp = lib.BinaryenConvertUInt64ToFloat32()
    ConvertUInt64ToFloat64: BinaryenOp = lib.BinaryenConvertUInt64ToFloat64()
    ConvertUVecI32x4ToVecF32x4: BinaryenOp = lib.BinaryenConvertUVecI32x4ToVecF32x4()
    CtzInt32: BinaryenOp = lib.BinaryenCtzInt32()
    CtzInt64: BinaryenOp = lib.BinaryenCtzInt64()
    DemoteFloat64: BinaryenOp = lib.BinaryenDemoteFloat64()
    DemoteZeroVecF64x2ToVecF32x4: BinaryenOp = lib.BinaryenDemoteZeroVecF64x2ToVecF32x4()
    EqZInt32: BinaryenOp = lib.BinaryenEqZInt32()
    EqZInt64: BinaryenOp = lib.BinaryenEqZInt64()
    ExtAddPairwiseSVecI16x8ToI32x4: BinaryenOp = lib.BinaryenExtAddPairwiseSVecI16x8ToI32x4()
    ExtAddPairwiseSVecI8x16ToI16x8: BinaryenOp = lib.BinaryenExtAddPairwiseSVecI8x16ToI16x8()
    ExtAddPairwiseUVecI16x8ToI32x4: BinaryenOp = lib.BinaryenExtAddPairwiseUVecI16x8ToI32x4()
    ExtAddPairwiseUVecI8x16ToI16x8: BinaryenOp = lib.BinaryenExtAddPairwiseUVecI8x16ToI16x8()
    ExtendHighSVecI16x8ToVecI32x4: BinaryenOp = lib.BinaryenExtendHighSVecI16x8ToVecI32x4()
    ExtendHighSVecI32x4ToVecI64x2: BinaryenOp = lib.BinaryenExtendHighSVecI32x4ToVecI64x2()
    ExtendHighSVecI8x16ToVecI16x8: BinaryenOp = lib.BinaryenExtendHighSVecI8x16ToVecI16x8()
    ExtendHighUVecI16x8ToVecI32x4: BinaryenOp = lib.BinaryenExtendHighUVecI16x8ToVecI32x4()
    ExtendHighUVecI32x4ToVecI64x2: BinaryenOp = lib.BinaryenExtendHighUVecI32x4ToVecI64x2()
    ExtendHighUVecI8x16ToVecI16x8: BinaryenOp = lib.BinaryenExtendHighUVecI8x16ToVecI16x8()
    ExtendLowSVecI16x8ToVecI32x4: BinaryenOp = lib.BinaryenExtendLowSVecI16x8ToVecI32x4()
    ExtendLowSVecI32x4ToVecI64x2: BinaryenOp = lib.BinaryenExtendLowSVecI32x4ToVecI64x2()
    ExtendLowSVecI8x16ToVecI16x8: BinaryenOp = lib.BinaryenExtendLowSVecI8x16ToVecI16x8()
    ExtendLowUVecI16x8ToVecI32x4: BinaryenOp = lib.BinaryenExtendLowUVecI16x8ToVecI32x4()
    ExtendLowUVecI32x4ToVecI64x2: BinaryenOp = lib.BinaryenExtendLowUVecI32x4ToVecI64x2()
    ExtendLowUVecI8x16ToVecI16x8: BinaryenOp = lib.BinaryenExtendLowUVecI8x16ToVecI16x8()
    ExtendS16Int32: BinaryenOp = lib.BinaryenExtendS16Int32()
    ExtendS16Int64: BinaryenOp = lib.BinaryenExtendS16Int64()
    ExtendS32Int64: BinaryenOp = lib.BinaryenExtendS32Int64()
    ExtendS8Int32: BinaryenOp = lib.BinaryenExtendS8Int32()
    ExtendS8Int64: BinaryenOp = lib.BinaryenExtendS8Int64()
    ExtendSInt32: BinaryenOp = lib.BinaryenExtendSInt32()
    ExtendUInt32: BinaryenOp = lib.BinaryenExtendUInt32()
    FloorFloat32: BinaryenOp = lib.BinaryenFloorFloat32()
    FloorFloat64: BinaryenOp = lib.BinaryenFloorFloat64()
    FloorVecF32x4: BinaryenOp = lib.BinaryenFloorVecF32x4()
    FloorVecF64x2: BinaryenOp = lib.BinaryenFloorVecF64x2()
    NearestFloat32: BinaryenOp = lib.BinaryenNearestFloat32()
    NearestFloat64: BinaryenOp = lib.BinaryenNearestFloat64()
    NearestVecF32x4: BinaryenOp = lib.BinaryenNearestVecF32x4()
    NearestVecF64x2: BinaryenOp = lib.BinaryenNearestVecF64x2()
    NegFloat32: BinaryenOp = lib.BinaryenNegFloat32()
    NegFloat64: BinaryenOp = lib.BinaryenNegFloat64()
    NegVecF32x4: BinaryenOp = lib.BinaryenNegVecF32x4()
    NegVecF64x2: BinaryenOp = lib.BinaryenNegVecF64x2()
    NegVecI16x8: BinaryenOp = lib.BinaryenNegVecI16x8()
    NegVecI32x4: BinaryenOp = lib.BinaryenNegVecI32x4()
    NegVecI64x2: BinaryenOp = lib.BinaryenNegVecI64x2()
    NegVecI8x16: BinaryenOp = lib.BinaryenNegVecI8x16()
    NotVec128: BinaryenOp = lib.BinaryenNotVec128()
    PopcntInt32: BinaryenOp = lib.BinaryenPopcntInt32()
    PopcntInt64: BinaryenOp = lib.BinaryenPopcntInt64()
    PopcntVecI8x16: BinaryenOp = lib.BinaryenPopcntVecI8x16()
    PromoteFloat32: BinaryenOp = lib.BinaryenPromoteFloat32()
    PromoteLowVecF32x4ToVecF64x2: BinaryenOp = lib.BinaryenPromoteLowVecF32x4ToVecF64x2()
    ReinterpretFloat32: BinaryenOp = lib.BinaryenReinterpretFloat32()
    ReinterpretFloat64: BinaryenOp = lib.BinaryenReinterpretFloat64()
    ReinterpretInt32: BinaryenOp = lib.BinaryenReinterpretInt32()
    ReinterpretInt64: BinaryenOp = lib.BinaryenReinterpretInt64()
    RelaxedTruncSVecF32x4ToVecI32x4: BinaryenOp = lib.BinaryenRelaxedTruncSVecF32x4ToVecI32x4()
    RelaxedTruncUVecF32x4ToVecI32x4: BinaryenOp = lib.BinaryenRelaxedTruncUVecF32x4ToVecI32x4()
    RelaxedTruncZeroSVecF64x2ToVecI32x4: BinaryenOp = lib.BinaryenRelaxedTruncZeroSVecF64x2ToVecI32x4()
    RelaxedTruncZeroUVecF64x2ToVecI32x4: BinaryenOp = lib.BinaryenRelaxedTruncZeroUVecF64x2ToVecI32x4()
    SplatVecF32x4: BinaryenOp = lib.BinaryenSplatVecF32x4()
    SplatVecF64x2: BinaryenOp = lib.BinaryenSplatVecF64x2()
    SplatVecI16x8: BinaryenOp = lib.BinaryenSplatVecI16x8()
    SplatVecI32x4: BinaryenOp = lib.BinaryenSplatVecI32x4()
    SplatVecI64x2: BinaryenOp = lib.BinaryenSplatVecI64x2()
    SplatVecI8x16: BinaryenOp = lib.BinaryenSplatVecI8x16()
    SqrtFloat32: BinaryenOp = lib.BinaryenSqrtFloat32()
    SqrtFloat64: BinaryenOp = lib.BinaryenSqrtFloat64()
    SqrtVecF32x4: BinaryenOp = lib.BinaryenSqrtVecF32x4()
    SqrtVecF64x2: BinaryenOp = lib.BinaryenSqrtVecF64x2()
    TruncFloat32: BinaryenOp = lib.BinaryenTruncFloat32()
    TruncFloat64: BinaryenOp = lib.BinaryenTruncFloat64()
    TruncSFloat32ToInt32: BinaryenOp = lib.BinaryenTruncSFloat32ToInt32()
    TruncSFloat32ToInt64: BinaryenOp = lib.BinaryenTruncSFloat32ToInt64()
    TruncSFloat64ToInt32: BinaryenOp = lib.BinaryenTruncSFloat64ToInt32()
    TruncSFloat64ToInt64: BinaryenOp = lib.BinaryenTruncSFloat64ToInt64()
    TruncSatSFloat32ToInt32: BinaryenOp = lib.BinaryenTruncSatSFloat32ToInt32()
    TruncSatSFloat32ToInt64: BinaryenOp = lib.BinaryenTruncSatSFloat32ToInt64()
    TruncSatSFloat64ToInt32: BinaryenOp = lib.BinaryenTruncSatSFloat64ToInt32()
    TruncSatSFloat64ToInt64: BinaryenOp = lib.BinaryenTruncSatSFloat64ToInt64()
    TruncSatSVecF32x4ToVecI32x4: BinaryenOp = lib.BinaryenTruncSatSVecF32x4ToVecI32x4()
    TruncSatUFloat32ToInt32: BinaryenOp = lib.BinaryenTruncSatUFloat32ToInt32()
    TruncSatUFloat32ToInt64: BinaryenOp = lib.BinaryenTruncSatUFloat32ToInt64()
    TruncSatUFloat64ToInt32: BinaryenOp = lib.BinaryenTruncSatUFloat64ToInt32()
    TruncSatUFloat64ToInt64: BinaryenOp = lib.BinaryenTruncSatUFloat64ToInt64()
    TruncSatUVecF32x4ToVecI32x4: BinaryenOp = lib.BinaryenTruncSatUVecF32x4ToVecI32x4()
    TruncSatZeroSVecF64x2ToVecI32x4: BinaryenOp = lib.BinaryenTruncSatZeroSVecF64x2ToVecI32x4()
    TruncSatZeroUVecF64x2ToVecI32x4: BinaryenOp = lib.BinaryenTruncSatZeroUVecF64x2ToVecI32x4()
    TruncUFloat32ToInt32: BinaryenOp = lib.BinaryenTruncUFloat32ToInt32()
    TruncUFloat32ToInt64: BinaryenOp = lib.BinaryenTruncUFloat32ToInt64()
    TruncUFloat64ToInt32: BinaryenOp = lib.BinaryenTruncUFloat64ToInt32()
    TruncUFloat64ToInt64: BinaryenOp = lib.BinaryenTruncUFloat64ToInt64()
    TruncVecF32x4: BinaryenOp = lib.BinaryenTruncVecF32x4()
    TruncVecF64x2: BinaryenOp = lib.BinaryenTruncVecF64x2()
    WrapInt64: BinaryenOp = lib.BinaryenWrapInt64()
